spring:
  application:
    name: kanban
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/kanban}
    username: ${DB_USERNAME:username}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      data-source-properties:
        tcpKeepAlive: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://dev-qprlf4kpcqixju57.us.auth0.com/}
          audiences: ${JWT_AUDIENCES:https://kanban-api}
springdoc:
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs
logging:
  level:
    root: INFO
    com.kylerriggs.kanban: DEBUG
kanban:
  security:
    custom-claim-prefix: https://kanban.kylerriggs.com/claims/
    cors-allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
  board:
    max-boards-per-user: 10
    default-columns:
      - Backlog
      - To Do
      - In Progress
      - Done
      - Canceled
